#!/bin/bash

OPTIONS="\
 Firefox \n\
 Telegram \n\
 Deadbeef \n\
 RoxFiler \n\
 Terminal \n\
 Smart-Term \n\
 Root-Terminal \n\
 Leafpad \n\
 Pinta \n\
 Transmission \n\
 Private Browser\n\
 Tor Browser\n\
 Pulsemixer \n\
 Wallpaper \n\
 Connman \n\
 Python \n\
 Lxtask \n\
 Arandr \n\
 Record Desktop \n\
 Screenshot \n\
 Retroarch \n\
 Dosbox \n\
 Virtualbox \n\
 Hold Alt_gr \n\
 Move North \n\
 Move West \n\
 Move East \n\
 Move South \n\
 Monocle Mode \n\
 Tile Mode \n\
 Floating Mode \n\
\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\
 Logoff\n\
 Suspend system\n\
 Reboot system\n\
 Power-off system"

LAUNCHER="			\
rofi                            \
-dmenu                          \
-location 1                     \
-lines 12                       \
-width 371                      \
-yoffset 19                     \
-columns 2                      \
-me-accept-entry MousePrimary   \
-me-select-entry MouseDPrimary  \
-p Menu				\
"

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval $1
        ;;
             )
        firefox
        ;;
            )
        telegram-desktop 
        ;;
            )
        deadbeef
        ;;
            )
        rox
        ;;
            )
        terminal
        ;;
            )
        smart-terminal
        ;;
            )
        root-terminal
        ;;
            )
        editor
        ;;
            )
        pinta
        ;;
            )
        transmission-gtk
        ;;
             )
        firefox --private-window
        ;;
             )
        ~/Packages/tor-browser_en-US/Browser/start-tor-browser
        ;;
            )
        st-arc -e pulsemixer
        ;;
            )
        wallpaper
        ;;
            )
        st-arc -e connmanctl
        ;;
            )
        python-shell
        ;;
            )
        lxtask
        ;;
            )
        arandr
        ;;
            )
        simplescreenrecorder
        ;;
            )
        sleep 0.5; screenshot
        ;;
            )
        flatpak run org.libretro.RetroArch
        ;;
            )
        flatpak run com.dosbox.DOSBox
        ;;
            )
        virtualbox
        ;;
            )
        alt_gr
        ;;
            )
        bspc node -s north
        ;;
            )
        bspc node -s west
        ;;
            )
        bspc node -s east
        ;;
            )
        bspc node -s south
        ;;
            )
        bspc desktop -l next
        ;;
            )
        bspc node -t tiled
        ;;
            )
        bspc node -t floating
        ;;
             )
        pkill bspwm
        ;;
            )
        slock systemctl suspend -i
        ;;
            )
        systemctl reboot
        ;;
            )
        systemctl poweroff
        ;;
      *)
        ;;
    esac
fi

